/// Flutter icons Umenaviicon1
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Umenaviicon1
///      fonts:
///       - asset: fonts/Umenaviicon1.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Umenaviicon1 {
  Umenaviicon1._();

  static const _kFontFam = 'Umenaviicon1';
  static const String _kFontPkg = null;

  static const IconData iconmonstr_map_2_240 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tetris_svgrepo_com = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData games = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_111651_256 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_158931_256 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
