name: GitHub Pages Release

on:
  push:
    branches:
      - webrelease
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Generate build number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}} 
      - name: Setup Flutter
        run: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b 2.2.1 _flutter
          echo "${GITHUB_WORKSPACE}/_flutter/bin" >> ${GITHUB_PATH}

      - name: Install
        run: |
          flutter config --enable-web
          flutter pub get
      - name: Build
        run: flutter build web --dart-define=APPVER="Build $BUILD_NUMBER"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/webrelease' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages_release
          publish_dir: ./build/web
